### ISSUE TITLE
Multi-platform for OwnCloud&NextCloud

### ISSUE THREAD

**Issue by flionet89** [LeonardoRM/owncloud-roundcube#7]
Hi. Is it possible to make this application work not only in OwnCloud but also in NextCloud?

**Comment by feltel** [comment]
I´m using the latest available code from Martin Reinhardt (https://github.com/hypery2k/owncloud/), where this fork is based on, on an NC13 instance. So there should be no problem running under NC up to version 13.0.x. Unfortunately this is the last Nextcloud version it will run due to API changes and probably PHP changes as well.  It would be awesome if I could use a more recent Nextcloud version with this plugin.

**Comment by LeonardoRM** [comment]
As long as Nextcloud API follows that of Owncloud, there shouldn't be problems. However this app is not built with Nextcloud in mind, it would require more effort if APIs fork in different paths.
